# Generated by Django 5.2.15 on 2026-07-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0003_project_and_run_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonrun',
            name='db1_schema',
            field=models.CharField(default='public', max_length=255, verbose_name='Esquema BD1'),
        ),
    ]
